### ISSUE TITLE
Request:  More events to support

### ISSUE THREAD

**Issue by tsprivate** [pokiiio/node-red-contrib-sonos-notify#2]
Hi, 

I really like your approach on Sonos-Events so we don't have a to listen and request updates permanently. I understand you are currently responding to track changes only.

Would it be possible (I don't know if the Sonos core node does support) to so support notification on:

- Play state changes (Play, Pause,Stop)
- Volume change
- MuteState change
- Playing progress (nice to have but not important)
- Line-In change

Thanks for considering

**Comment by pokiiio** [comment]
thanks for a comment, I'm planning feature like you mentioned.
let me code these, and I'll release soon.

**Comment by tsprivate** [comment]
The new events are working great!   thx a lot
